name: UiPathBuildDeploy
on:
  push:
    branches: [ main ]
jobs:
 remove-old-artifacts:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
 Build:
    runs-on: windows-latest
    needs: remove-old-artifacts
    steps:            
      # Checkout code from this repo
      - name: Checkout Code
        uses: actions/checkout@v2      
      # Facilitate the UiPath CLI in the github artifacts
      - name: Get UiPath CLI
        run: |
                 New-Item -Path "C:\\" -ItemType "directory" -Name "uipathcli";
                 Invoke-WebRequest "https://uipath.pkgs.visualstudio.com/Public.Feeds/_apis/packaging/feeds/1c781268-d43d-45ab-9dfc-0151a1c740b7/nuget/packages/UiPath.CLI.Windows/versions/23.6.8581.19168/content" -OutFile "C:\\uipathcli\\cli.zip";
                 Expand-Archive -LiteralPath "C:\\uipathcli\\cli.Zip" -DestinationPath "C:\\uipathcli";
     
      - name: "Run Process"
        run: |         
          "C:\\uipathcli\\tools\\uipcli.exe" --process "BasicTest" "https://staging.uipath.com/" "${{secrets.TENANT_NAME}}" -A ${{secrets.ACCOUNT_NAME}} -I ${{secrets.OAUTH_CLIENT_ID}} -S "${{secrets.OAUTH_CLIENT_SECRET}}" -o "Shared" --applicationScope "${{secrets.OAUTH_CLIENT_SCOPES}}"
